name: General CI

# this file is a joint CI of parachain and tee-worker, it contains:
# - build (of docker images)
# - format check
# - unit tests
# - integration tests

# Some notes:
#
# [1] the tee-worker part is a modified version of tee-worker/.github/workflows/build_and_test.yml
# with extra triggering control.
#
# [2] the original file (`tee-worker/.github/workflows/build_and_test.yml`) is kept to sync
# upstream changes, therefore we need to manually apply the changes to this file.

# [3] please beware that if a job in `needs` is skipped, its dependent job will also be skipped,
# see https://github.com/actions/runner/issues/491
#
# jobs that will always be executed:
# - fmt
# - set-condition
# - parachain-build
# - tee-build
#
# [4] please note that job-level if `env` is not supported:
# https://github.com/actions/runner/issues/1189
# as a workaround, we need to put it in a step-level or use `needs.outputs`

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
    inputs:
      rebuild-parachain-docker:
        type: boolean
        description: rebuild-parachain-docker
        required: true
        default: true
      rebuild-tee-docker:
        type: boolean
        description: rebuild-tee-docker
        required: true
        default: true
      push-docker:
        type: boolean
        description: push-docker
        required: true
        default: fasle

env:
  CARGO_TERM_COLOR: always
  DOCKER_BUILDKIT: 1
  # the branch or tag on which this workflow is triggered
  # `head_ref` will only be set if the triggering event is `pull_request`
  REF_VERSION: ${{ github.head_ref || github.ref_name }}

concurrency:
  # see https://stackoverflow.com/questions/74117321/if-condition-in-concurrency-in-gha
  # along with the `sequentialise` job below, it guarantees:
  # - for push in dev: all triggered CIs will be run sequentially, none is cancelled
  # - for PR: later triggered CIs will cancel previous runs, maximum one CI will be run
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  set-condition:
    runs-on: ubuntu-latest
    # see https://github.com/orgs/community/discussions/25722
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    outputs:
      rebuild_parachain: ${{ steps.env.outputs.rebuild_parachain }}
      rebuild_tee: ${{ steps.env.outputs.rebuild_tee }}
      push_docker: ${{ steps.env.outputs.push_docker }}
      run_parachain_test: ${{ steps.env.outputs.run_parachain_test }}
      run_tee_test: ${{ steps.env.outputs.run_tee_test }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Checks to see if any files in the PR/commit match one of the listed file types.
      # We can use this filter to decide whether or not to build docker images
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/file-filter.yml
          list-files: shell

      - name: Set condition
        id: env
        run: |
          rebuild_parachain=false
          rebuild_tee=false
          push_docker=false
          run_parachain_test=false
          run_tee_test=false
          if [ "${{ github.event.inputs.rebuild-parachain-docker }}" = "true" ] || [ "${{ steps.filter.outputs.parachain_src }}" = "true" ]; then
            rebuild_parachain=true
          fi
          if [ "${{ github.event.inputs.rebuild-tee-docker }}" = "true" ] || [ "${{ steps.filter.outputs.tee_src }}" = "true" ]; then
            rebuild_tee=true
          fi
          if [ "${{ github.event.inputs.push-docker }}" = "true" ]; then
            push_docker=true
          elif [ "${{ github.event_name }}" = 'push' ] && [ "${{ github.ref }}" = 'refs/heads/dev' ]; then
            push_docker=true
          fi
          if [ "${{ steps.filter.outputs.parachain_test }}" = "true" ] || [ "$rebuild_parachain" = "true" ]; then
            run_parachain_test=true
          fi
          if [ "${{ steps.filter.outputs.tee_test }}" = "true" ] || [ "$rebuild_parachain" = "true" ] || [ "$rebuild_tee" = "true" ]; then
            run_tee_test=true
          fi
          echo "rebuild_parachain=$rebuild_parachain" | tee -a $GITHUB_OUTPUT
          echo "rebuild_tee=$rebuild_tee" | tee -a $GITHUB_OUTPUT
          echo "push_docker=$push_docker" | tee -a $GITHUB_OUTPUT
          echo "run_parachain_test=$run_parachain_test" | tee -a $GITHUB_OUTPUT
          echo "run_tee_test=$run_tee_test" | tee -a $GITHUB_OUTPUT

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        run: rustup show

      - name: Install pre-built taplo
        run: |
          mkdir -p $HOME/.local/bin
          wget -q https://github.com/tamasfe/taplo/releases/latest/download/taplo-linux-x86_64.gz
          gzip -d taplo-linux-x86_64.gz
          cp taplo-linux-x86_64 $HOME/.local/bin/taplo
          chmod a+x $HOME/.local/bin/taplo
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Parachain fmt check
        run: |
          make fmtcheck
          make taplocheck

      - name: Tee-worker fmt check
        working-directory: ./tee-worker
        run: |
          cargo fmt --all -- --check
          taplo fmt --check

      - name: Enclave-runtime fmt check
        working-directory: ./tee-worker/enclave-runtime
        run: |
          cargo fmt --all -- --check

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  # sequentialise the workflow runs on `dev` branch
  # the if condition is applied in step level to make this job always `successful`
  sequentialise:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for previous run
        if: ${{ !failure() && (github.event_name == 'push') && (github.ref == 'refs/heads/dev') }}
        uses: mktcode/consecutive-workflow-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 300
          branch: dev

  parachain-clippy:
    runs-on: ubuntu-latest
    needs:
      - fmt
      - set-condition
      - sequentialise
    if: needs.set-condition.outputs.rebuild_parachain == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        run: rustup show

      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -yq openssl clang libclang-dev cmake protobuf-compiler

      - name: Run cargo clippy check
        run: make clippy

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  tee-clippy:
    runs-on: ubuntu-latest
    needs:
      - fmt
      - set-condition
      - sequentialise
    if: needs.set-condition.outputs.rebuild_tee == 'true'
    container: "integritee/integritee-dev:0.1.12"
    steps:
      - uses: actions/checkout@v3

      - name: Tee-worker clippy
        working-directory: ./tee-worker
        run: |
          rustup show
          cargo clippy -- -D warnings
          cargo clippy --features evm -- -D warnings
          cargo clippy --features sidechain -- -D warnings
          cargo clippy --features teeracle -- -D warnings
          cargo clippy --features offchain-worker -- -D warnings

      - name: Tee-enclave clippy
        working-directory: ./tee-worker/enclave-runtime
        run: |
          rustup show
          cargo clippy -- -D warnings
          cargo clippy --features evm -- -D warnings
          cargo clippy --features sidechain -- -D warnings
          cargo clippy --features teeracle -- -D warnings
          cargo clippy --features offchain-worker -- -D warnings

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  parachain-build:
    runs-on: ubuntu-latest
    needs:
      - fmt
      - set-condition
      - sequentialise
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        if: needs.set-condition.outputs.rebuild_parachain == 'true'
        run: |
          make build-docker-release
          echo "============================="
          docker images

      - name: Pull docker image optinally
        if: needs.set-condition.outputs.rebuild_parachain == 'false'
        run: |
          docker pull litentry/litentry-parachain

      - name: Save docker image
        run: |
          docker save litentry/litentry-parachain -o litentry-parachain.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v3
        with:
          name: parachain-artifact
          path: litentry-parachain.tar
          if-no-files-found: error

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  tee-build:
    runs-on: ubuntu-20.04
    needs:
      - fmt
      - set-condition
      - sequentialise
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver: docker-container

      - name: Build worker (sidechain)
        if: needs.set-condition.outputs.rebuild_tee == 'true'
        env:
          DOCKER_BUILDKIT: 1
        run: >
          docker build -t litentry/integritee-worker
          --target deployed-worker
          --build-arg WORKER_MODE_ARG=sidechain --build-arg ADDITIONAL_FEATURES_ARG=
          -f tee-worker/build.Dockerfile .

      - name: Build cli (sidechain)
        if: needs.set-condition.outputs.rebuild_tee == 'true'
        env:
          DOCKER_BUILDKIT: 1
        run: >
          docker build -t litentry/integritee-cli
          --target deployed-client
          --build-arg WORKER_MODE_ARG=sidechain --build-arg ADDITIONAL_FEATURES_ARG=
          -f tee-worker/build.Dockerfile .

      - name: Pull and tag worker and cli image optionally
        if: needs.set-condition.outputs.rebuild_tee == 'false'
        run: |
          docker pull litentry/integritee-worker
          docker pull litentry/integritee-cli

      - run: docker images --all

      - name: Test enclave
        # cargo test is not supported in the enclave
        # see https://github.com/apache/incubator-teaclave-sgx-sdk/issues/232
        run: docker run litentry/integritee-worker test --all
        continue-on-error: true

      - name: Save docker images
        run: docker save litentry/integritee-worker litentry/integritee-cli -o litentry-tee.tar

      - name: Upload docker images
        uses: actions/upload-artifact@v3
        with:
          name: tee-artifact
          path: litentry-tee.tar
          if-no-files-found: error

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  parachain-ts-test:
    runs-on: ubuntu-latest
    needs:
      - set-condition
      - parachain-build
    strategy:
      matrix:
        chain:
          - litmus
          - litentry
          - rococo
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: parachain-artifact

      - name: Load docker image
        run: |
          docker load -i litentry-parachain.tar

      - name: Run ts tests for ${{ matrix.chain }}
        if: needs.set-condition.outputs.run_parachain_test == 'true'
        timeout-minutes: 20
        run: |
          make test-ts-docker-${{ matrix.chain }}

      - name: Archive logs if test fails
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ matrix.chain }}-ts-tests-artifacts
          path: /tmp/parachain_dev/
          if-no-files-found: ignore
          retention-days: 3

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  parachain-unit-test:
    runs-on: ubuntu-latest
    needs:
      - fmt
      - set-condition
      - sequentialise
    # run_parachain_test is related to ts-tests only
    if: needs.set-condition.outputs.rebuild_parachain == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Run unittests
        run: |
          rustup show
          # no `skip-ias-check` feature
          cargo test --locked --release -p pallet-* --lib
          # with `skip-ias-check` feature only
          cargo test --locked --release -p pallet-* --lib --features=skip-ias-check
          # with `runtime-benchmarks` feature only
          cargo test --locked --release -p pallet-* --lib --features=runtime-benchmarks
          # with both `skip-ias-check` and `runtime-benchmarks` features
          cargo test --locked --release -p pallet-* --lib --features=skip-ias-check,runtime-benchmarks

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  parachain-runtime-test:
    runs-on: ubuntu-latest
    needs:
      - fmt
      - set-condition
      - sequentialise
    # run_parachain_test is related to ts-tests only
    if: needs.set-condition.outputs.rebuild_parachain == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup show

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -yq openssl clang libclang-dev cmake protobuf-compiler

      # We could use matrix but don't have to. Since this ci has many jobs already,
      # we execute the runtime tests sequentially for a cleaner GHA visualisation graph.
      # It won't take much longer as we run them back to back.
      # We intentionally write 3 steps for better readability in GHA tab if one of them fails.
      - name: Run rococo runtime test
        run: cargo test --locked --release -p rococo-parachain-runtime --lib

      - name: Run litmus runtime test
        run: cargo test --locked --release -p litmus-parachain-runtime --lib

      - name: Run litentry runtime test
        run: cargo test --locked --release -p litentry-parachain-runtime --lib

      - name: Fail early
        if: failure()
        uses: andymckay/cancel-action@0.3

  tee-test:
    runs-on: ubuntu-latest
    needs:
      - set-condition
      - parachain-build
      - tee-build
    env:
      WORKER_IMAGE_TAG: integritee-worker:dev
      CLIENT_IMAGE_TAG: integritee-cli:dev
      COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
      TEERACLE_INTERVAL_SECONDS: 4

    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: demo-indirect-invocation
          - test_name: demo-direct-call
          - test_name: demo-sidechain
          # Litentry
          - test_name: lit-user-shielding-key
          - test_name: lit-resume-worker
          - test_name: lit-set-heartbeat-timeout
          - test_name: lit-vc-test
          - test_name: lit-identity-test
          - test_name: lit-batch-test

    steps:
      - uses: actions/checkout@v3

      - name: Pull polkadot image
        run: |
          docker pull parity/polkadot

      - uses: actions/download-artifact@v3
        with:
          name: parachain-artifact

      - uses: actions/download-artifact@v3
        with:
          name: tee-artifact

      - name: Load docker image
        run: |
          docker load -i litentry-parachain.tar
          docker load -i litentry-tee.tar

      - name: Re-name Image Tags
        run: |
          docker tag litentry/integritee-worker ${{ env.WORKER_IMAGE_TAG }}
          docker tag litentry/integritee-cli ${{ env.CLIENT_IMAGE_TAG }}
          docker images --all

      - name: Generate parachain artefacts
        run: |
          ./tee-worker/scripts/litentry/generate_parachain_artefacts.sh

      - name: Build litentry parachain docker images
        run: |
          cd tee-worker/docker
          docker compose -f litentry-parachain.build.yml build

      - name: Integration Test ${{ matrix.test_name }}
        if: needs.set-condition.outputs.run_tee_test == 'true'
        timeout-minutes: 30
        run: |
          cd tee-worker/docker
          if [ "${{ matrix.test_name }}" = "lit-resume-worker" ]; then
            docker compose -f docker-compose.yml -f ${{ matrix.test_name }}.yml up --no-build --exit-code-from ${{ matrix.test_name }} \
            --attach ${{ matrix.test_name }} relaychain-alice relaychain-bob integritee-node ${{ matrix.test_name }}
          else
            docker compose -f docker-compose.yml -f ${{ matrix.test_name }}.yml up --no-build --exit-code-from ${{ matrix.test_name }} -- ${{ matrix.test_name }}
          fi

      - name: Stop docker containers
        if: needs.set-condition.outputs.run_tee_test == 'true'
        run: |
          cd tee-worker/docker
          docker compose -f docker-compose.yml -f ${{ matrix.test_name }}.yml stop

      - name: Collect Docker Logs
        continue-on-error: true
        if: always()
        uses: jwalton/gh-docker-logs@v2
        with:
          tail: all
          dest: logs

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ matrix.test_name }}
          path: logs
          if-no-files-found: ignore

  # Secrets are not passed to the runner when a workflow is triggered from a forked repository,
  # see https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
  #
  # Only try to push docker image when
  #   - parachain-ts-test passes
  #   - tee-test passes
  #   - set-condition.outputs.push_docker is `true`
  # Whether the parachain or tee-worker image will actually be pushed still depends on if a new image was built/rebuilt.
  # This is important not to overwrite any other jobs where a rebuild **was** triggered.
  #
  # We don't have to depend on jobs like `parachain-unit-test` as they have the same trigger condition `rebuild_parachain`,
  # so there must be no new image if `parachain-unit-test` is skipped.
  #
  # `!failure()` needs to be used to cover skipped jobs
  push-docker:
    runs-on: ubuntu-latest
    needs:
      - set-condition
      - parachain-ts-test
      - tee-test
    if: ${{ !failure() && needs.set-condition.outputs.push_docker == 'true' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: parachain-artifact

      - uses: actions/download-artifact@v3
        with:
          name: tee-artifact

      - name: Load docker image
        run: |
          docker load -i litentry-parachain.tar
          docker load -i litentry-tee.tar

      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # only push the docker image if we rebuilt it
      - name: Push parachain image
        if: needs.set-condition.outputs.rebuild_parachain == 'true'
        run: |
          docker push litentry/litentry-parachain

      # only push the docker image if we rebuilt it
      - name: Push tee-worker image
        if: needs.set-condition.outputs.rebuild_tee == 'true'
        run: |
          docker push litentry/integritee-worker
          docker push litentry/integritee-cli
